# Generated by Django 4.1.3 on 2022-11-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_itenscompras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itenscompras',
            options={'verbose_name_plural': 'Itens da Compra'},
        ),
    ]
